### PR TITLE
Added forward compatibility with Python 3

### PR DESCRIPTION
**Pull request by manuel219**
Changed all `print x` statements to the `print(x)` function for Python 3 compatibility and imported the appropiate `__future__` package to maintain compatibility with Python 2.

GAH! WHY IS CONFLICT RESOLUTION SO HARD!?

### CODE REVIEW

**Comment by obskyr** [comment]
:kissing_heart:! Thanks!

**Comment by manuel219** [comment]
No problem!

I should probably delete my fork now, correct?

**Comment by obskyr** [comment]
You can, but to me it doesn't make any difference, really. Keep it if you want to keep it (shows up on your profile, shows up as a +1 by "Fork" in this repo, etc.), or delete it if you want to do that. Now that it's merged it doesn't really matter.

**Comment by manuel219** [comment]
Yeah, though so. Guess I'll delete it since my commit is on this repository's history anyways.

**Pull request merged**
