### PR TITLE
Made strings unicode safe before printing

### PR DESCRIPTION
**Pull request by manuel219**
Made every string use <type 'unicode'> instead of <type 'str'> and UTF-8 encoding before being printed.
Fixes non-ASCII song names throwing a UnicodeError. Though, file names are wierd (e.g.: 'é' is written as 'Ã©').

Also changed print to use 'print(x)' instead of 'print x' because of PEP 3105.

### CODE REVIEW

**Comment by obskyr** [comment]
Is there a reason that you've added `.encode('utf-8')` to literally every single string in the program? On line 73, for example: `ostName=u"".encode('utf-8')`. This returns `""` - of the type `str` - which just plain `""` was in the first place.

Sorry, but if there isn't a good reason for adding this everywhere, I can't merge this pull request.

**Comment by manuel219** [comment]
Oops, sorry about that, accidentally committed the wrong file.

The pull request is now just changing strings to use type `unicode` and changing `print` statements into the `print()` function.

(I'm so sorry, I'm a complete noob at version control, much less git.)

**Comment by manuel219** [comment]
By the by, the reason I changed the script to use type `unicode` is because it would fail to download songs with non-ASCII characters in the name (e.g.: `é`, `ñ` or `醵`) and throw `UnicodeError`. The reason being that you were using `.format()` on a type `str` and the song's name would be a type `unicode` in those cases (which cannot be concatenated with a type `str`).

The reason for replacing `print` with `print()` is merely convention. See [PEP 3105](https://www.python.org/dev/peps/pep-3105/).

Sorry if the reason for this pull was unclear.

**Comment by obskyr** [comment]
Generally, pull requests contain only one change / one type of change, and if the contributor wants to make other unrelated changes, those are in a separate pull request. This is so changes can be individually approved.

This is the case here - I would love to merge the fix for sountracks containing special characters! I would however not love to merge the change of all the print calls from `print` to `print()` (PEP 3105 specifies a change to the language in Python 3, not a convention in Python 2, which `khinsider.py` is written in), and not the change from `""` to `u""` everywhere (unless that provides any benefit on these raw strings, which I don't think).

If you make a pull request with just the fix, I'd be happy to accept that! Super nice of you to notice and solve the problem. As it is now, though, I don't really want to merge.

**Pull request closed without merging**
